[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

board_build.filesystem = littlefs

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_BT_NIMBLE_MAX_BONDS=3

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
    fastled/FastLED@^3.7.0
    mathieucarbou/ESPAsyncWebServer@^3.3.0
    mathieucarbou/AsyncTCP@^3.2.0
    bblanchon/ArduinoJson@^7.0.0
